package io.github.fergoman123.msb.info;

public class BlockNames {
    public static final String blockCharcoal = "blockCharcoal";
    public static final String blockApple = "blockApple";
    public static final String blockGoldApple = "blockGoldApple";
    public static final String blockBook = "blockBook";
    public static final String blockEgg = "blockEgg";
    public static final String blockEnder = "blockEnder";
    public static final String blockLead = "blockLead";
    public static final String blockReed = "blockReed";
    public static final String blockSeeds = "blockSeeds";
    public static final String blockStick = "blockStick";
    public static final String blockLeather = "blockLeather";
    public static final String blockBucket = "blockBucket";
    public static final String blockDye = "blockDye";
    public static final String blockFireball = "blockFireball";
    public static final String blockSlimeball = "blockSlimeball";
    public static final String blockRottenFlesh = "blockRottenFlesh";
    public static final String blockPotato = "blockPotato";
    public static final String blockNetherWart = "blockNetherWart";
    public static final String blockGunpowder = "blockGunpowder";
    public static final String blockCarrot = "blockCarrot";
    public static final String blockArrow = "blockArrow";
    public static final String blockBlazeRod = "blockBlazeRod";
    public static final String blockFlint = "blockFlint";
    public static final String blockBone = "blockBone";
    public static final String blockSugar = "blockSugar";
    public static final String blockNetherStar = "blockNetherStar";
    public static final String blockClay = "blockClay";
    public static final String blockString = "blockString";
    public static final String blockFeather = "blockFeather";
    public static final String blockBread = "blockBread";
    public static final String blockPorkchop = "blockPorkchop";
    public static final String blockFish = "blockFish";
    public static final String blockCookie = "blockCookie";
    public static final String blockBeef = "blockBeef";
    public static final String blockPumpkinPie = "blockPumpkinPie";
    public static final String blockGhastTear = "blockGhastTear";
    public static final String blockSkull = "blockSkull";
    public static final String blockMutton = "blockMutton";
    public static final String blockRabbit = "blockRabbit";
    public static final String blockCompCobble = "blockCompCobble";
    public static final String blockCompSand = "blockCompSand";
    public static final String blockCompGravel = "blockCompGravel";
}
