package io.github.fergoman123.msb.info;

public class BlockNames
{
    public static final String blockCharcoal = "blockCharcoal";
    public static final String blockApple = "blockApple";
    public static final String blockGoldAppleName = "blockGA";
    public static final String[] blockGoldApple = {"blockGoldApple1", "blockGoldApple2"};
    public static final String blockBook = "blockBook";
    public static final String blockEgg = "blockEgg";
    public static final String blockEnderPearl = "blockEnderPearl";
    public static final String blockEnderEye = "blockEnderEye";
    public static final String blockLead = "blockLead";
    public static final String blockReed = "blockReed";
    public static final String blockSeedsName = "blockSeeds";
    public static final String[] blockSeeds = {"blockWheatSeeds", "blockPumpkinSeeds", "blockMelonSeeds"};
    public static final String blockStick = "blockStick";
    public static final String blockLeather = "blockLeather";
    public static final String blockBucket = "blockBucket";
    public static final String blockDyeName = "blockDye";
    public static final String[] blockDye = {"blockInkSack", "blockRoseRed", "blockCactusGreen", "blockCocoa", "blockPurpleDye", "blockCyanDye", "blockSilverDye", "blockGrayDye", "blockPinkDye", "blockLimeDye", "blockYellowDye", "blockLightBlueDye", "blockMagentaDye", "blockOrangeDye", "blockWhiteDye"};
    public static final String blockFireball = "blockFireball";
    public static final String blockSlimeball = "blockSlimeball";
    public static final String blockRottenFlesh = "blockRottenFlesh";
    public static final String blockPotato = "blockPotato";
    public static final String blockNetherWart = "blockNetherWart";
    public static final String blockGunpowder = "blockGunpowder";
    public static final String blockCarrot = "blockCarrot";
    public static final String blockArrow = "blockArrow";
    public static final String blockBlazeRod = "blockBlazeRod";
    public static final String blockFlint = "blockFlint";
    public static final String blockBone = "blockBone";
    public static final String blockSugar = "blockSugar";
    public static final String blockNetherStar = "blockNetherStar";
    public static final String blockClay = "blockClay";
    public static final String blockString = "blockString";
    public static final String blockFeather = "blockFeather";
    public static final String blockBread = "blockBread";
    public static final String blockPorkchopName = "blockPorkchop";
    public static final String[] blockPorkchop = {"blockRawPorkchop", "blockCookedPorkchop"};
    public static final String blockFishName = "blockFish";
    public static final String[] blockFish = {"blockRawFish", "blockRawSalmon", "blockClownfish", "blockPufferfish", "blockCookedFish", "blockCookedSalmon"};
    public static final String blockCookie = "blockCookie";
    public static final String blockBeefName = "blockBeef";
    public static final String[] blockBeef = {"blockRawBeef", "blockCookedBeef"};
    public static final String blockPumpkinPie = "blockPumpkinPie";
    public static final String blockGhastTear = "blockGhastTear";
    public static final String blockSkullName = "blockSkull";
    public static final String[] blockSkull = {"blockSkullSkeleton", "blockSkullWither", "blockSkullZombie", "blockSkullCreeper"};
}
