package io.github.fergoman123.msb.info;

import net.minecraftforge.fml.common.ModMetadata;

public class MetadataMSB
{
    public static void writeMetadata(ModMetadata md)
    {
        md.autogenerated = false;
        md.modId = ModInfo.modid;
        md.name = ModInfo.name;
        md.version = ModInfo.version;
        md.description = ModInfo.desc;
        md.authorList = ModInfo.authorList;
        md.logoFile = ModInfo.logoFile;
        md.url = ModInfo.url;
        md.updateUrl = ModInfo.updateUrl;
    }
}
