 /*
  * More Storage Blocks
  * Copyright (c) 2014 fergoman123.
  * All rights reserved. This program and the accompanying materials
  * are made available under the terms of the GNU Lesser Public License v2.1
  * which accompanies this distribution, and is available at
  * http://www.gnu.org/licenses/gpl-3.0.html
  */

package fergoman123.mods.msb.reference;

import cpw.mods.fml.common.ModMetadata;

public class MetadataMSB
{
    public static void writeMetadata(ModMetadata md)
    {
        md.autogenerated = false;
        md.modId = ModInfo.modid;
        md.name = ModInfo.name;
        md.version = ModInfo.versionMain;
        md.description = ModInfo.desc;
        md.authorList = ModInfo.authors;
        md.logoFile = ModInfo.logoFile;
        md.url = ModInfo.url;
        md.updateUrl = ModInfo.updateUrl;
    }

}
