package fergoman123.mods.msb.reference;

import cpw.mods.fml.common.ModMetadata;

public class MetadataMSB
{
    public static void writeMetadata(ModMetadata md)
    {
        md.autogenerated = false;
        md.modId = ModInfo.modid;
        md.name = ModInfo.name;
        md.version = ModInfo.versionMain;
        md.description = ModInfo.desc;
        md.authorList = ModInfo.authors;
        md.logoFile = ModInfo.logoFile;
        md.url = ModInfo.url;
        md.updateUrl = ModInfo.updateUrl;
    }

}
