package io.github.fergoman123.msb.util;

import io.github.fergoman123.msb.init.ModBlocks;
import io.github.fergoman123.msb.itemblock.*;
import io.github.fergoman123.msb.reference.Names;
import net.minecraft.block.Block;
import net.minecraft.item.ItemBlock;

public class Utils
{
    public static final Class<? extends ItemBlock>[] itemblocks = new Class[]
            {
                    ItemBlockApple.class,
                    ItemBlockArrow.class,
                    ItemBlockBlazeRod.class,
                    ItemBlockBook.class,
                    ItemBlockCarrot.class,
                    ItemBlockCharcoal.class,
                    ItemBlockDye.class,
                    ItemBlockEgg.class,
                    ItemBlockEnderPearl.class,
                    ItemBlockEnderEye.class,
                    ItemBlockGoldApple.class,
                    ItemBlockGunpowder.class,
                    ItemBlockNetherWart.class,
                    ItemBlockPotato.class,
                    ItemBlockRottenFlesh.class,
                    ItemBlockSlimeball.class,
                    ItemBlockFireball.class,
                    ItemBlockSeeds.class,
                    ItemBlockLead.class,
                    ItemBlockLeather.class,
                    ItemBlockBucket.class,
                    ItemBlockStick.class,
                    ItemBlockFlint.class,
                    ItemBlockBone.class,
                    ItemBlockSugarcane.class,
                    ItemBlockSugar.class,
                    ItemBlockNetherStar.class,
                    ItemBlockClay.class,
                    ItemBlockString.class,
                    ItemBlockFeather.class,
                    ItemBlockBread.class,
                    ItemBlockPorkchop.class,
                    ItemBlockFish.class,
                    ItemBlockCookie.class,
                    ItemBlockBeef.class,
                    ItemBlockPumpkinPie.class,
                    ItemBlockGhastTear.class,
                    ItemBlockSkull.class
            };

    public static final String[] blockNames =
            {
                    Names.Blocks.blockApple,
                    Names.Blocks.blockArrow,
                    Names.Blocks.blockBlazeRod,
                    Names.Blocks.blockBook,
                    Names.Blocks.blockCarrot,
                    Names.Blocks.blockCharcoal,
                    Names.Blocks.blockDyeName,
                    Names.Blocks.blockEgg,
                    Names.Blocks.blockEnderPearl,
                    Names.Blocks.blockEnderEye,
                    Names.Blocks.blockGoldAppleName,
                    Names.Blocks.blockGunpowder,
                    Names.Blocks.blockNetherWart,
                    Names.Blocks.blockPotato,
                    Names.Blocks.blockRottenFlesh,
                    Names.Blocks.blockSlimeball,
                    Names.Blocks.blockFireball,
                    Names.Blocks.blockSeedsName,
                    Names.Blocks.blockLead,
                    Names.Blocks.blockLeather,
                    Names.Blocks.blockBucket,
                    Names.Blocks.blockStick,
                    Names.Blocks.blockFlint,
                    Names.Blocks.blockBone,
                    Names.Blocks.blockSugarcane,
                    Names.Blocks.blockSugar,
                    Names.Blocks.blockNetherStar,
                    Names.Blocks.blockClay,
                    Names.Blocks.blockString,
                    Names.Blocks.blockFeather,
                    Names.Blocks.blockBread,
                    Names.Blocks.blockPorkchopName,
                    Names.Blocks.blockFishName,
                    Names.Blocks.blockCookie,
                    Names.Blocks.blockBeefName,
                    Names.Blocks.blockPumpkinPie,
                    Names.Blocks.blockGhastTear,
                    Names.Blocks.blockSkull
            };

    public static final Block[] blocksList = new Block[]
            {
                    ModBlocks.blockApple,
                    ModBlocks.blockArrow,
                    ModBlocks.blockBlazeRod,
                    ModBlocks.blockBook,
                    ModBlocks.blockCarrot,
                    ModBlocks.blockCharcoal,
                    ModBlocks.blockDye,
                    ModBlocks.blockEgg,
                    ModBlocks.blockEnderPearl,
                    ModBlocks.blockEnderEye,
                    ModBlocks.blockGoldApple,
                    ModBlocks.blockGunpowder,
                    ModBlocks.blockNetherWart,
                    ModBlocks.blockPotato,
                    ModBlocks.blockRottenFlesh,
                    ModBlocks.blockSlimeball,
                    ModBlocks.blockFireball,
                    ModBlocks.blockSeeds,
                    ModBlocks.blockLead,
                    ModBlocks.blockLeather,
                    ModBlocks.blockBucket,
                    ModBlocks.blockStick,
                    ModBlocks.blockFlint,
                    ModBlocks.blockBone,
                    ModBlocks.blockSugarcane,
                    ModBlocks.blockSugar,
                    ModBlocks.blockNetherStar,
                    ModBlocks.blockClay,
                    ModBlocks.blockString,
                    ModBlocks.blockFeather,
                    ModBlocks.blockBread,
                    ModBlocks.blockPorkchop,
                    ModBlocks.blockFish,
                    ModBlocks.blockCookie,
                    ModBlocks.blockBeef,
                    ModBlocks.blockPumpkinPie,
                    ModBlocks.blockGhastTear,
                    ModBlocks.blockSkull
            };
}
