package io.github.fergoman123.msb.init;

import io.github.fergoman123.msb.block.*;
import io.github.fergoman123.msb.info.BlockNames;
import io.github.fergoman123.msb.item.ItemBlockEnder;
import io.github.fergoman123.msb.item.ItemBlockGoldApple;
import io.github.fergoman123.msb.item.ItemBlockMultiMSB;
import net.minecraft.block.Block;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.ModelBakery;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;

import static io.github.fergoman123.msb.helper.MSBHelper.registerBlock;

public class ModBlocks {
	public static Block blockCharcoal;
	public static Block blockApple;
	public static Block blockGoldApple;
	public static Block blockBook;
	public static Block blockEgg;
	public static Block blockEnder;
	public static Block blockLead;
	public static Block blockReed;
	public static Block blockSeeds;
	public static Block blockStick;
	public static Block blockLeather;
	public static Block blockBucket;
	public static Block blockDye;
	public static Block blockFireball;
	public static Block blockSlimeball;
	public static Block blockRottenFlesh;
	public static Block blockPotato;
	public static Block blockNether;
	public static Block blockGunpowder;
	public static Block blockCarrot;
	public static Block blockArrow;
	public static Block blockBlazeRod;
	public static Block blockFlint;
	public static Block blockBone;
	public static Block blockSugar;
	public static Block blockClay;
	public static Block blockString;
	public static Block blockFeather;
	public static Block blockBread;
	public static Block blockPorkchop;
	public static Block blockFish;
	public static Block blockCookie;
	public static Block blockBeef;
	public static Block blockPumpkinPie;
	public static Block blockGhastTear;
	public static Block blockSkull;
	public static Block blockMutton;
	public static Block blockRabbit;
	public static Block blockCompCobble;
	public static Block blockCompSand;
	public static Block blockCompGravel;

	public static void addBlocks() {
		blockCharcoal = new BlockMSB(BlockNames.blockCharcoal);
		blockApple = new BlockMSB(BlockNames.blockApple);
		blockGoldApple = new BlockGoldApple(BlockNames.blockGoldApple);
		blockBook = new BlockMSB(BlockNames.blockBook);
		blockEgg = new BlockMSB(BlockNames.blockEgg);
		blockEnder = new BlockEnder(BlockNames.blockEnder);
		blockLead = new BlockMSB(BlockNames.blockLead);
		blockReed = new BlockMSB(BlockNames.blockReed);
		blockSeeds = new BlockSeeds(BlockNames.blockSeeds);
		blockStick = new BlockMSB(BlockNames.blockStick);
		blockLeather = new BlockMSB(BlockNames.blockLeather);
		blockBucket = new BlockMSB(BlockNames.blockBucket);
		blockDye = new BlockDye(BlockNames.blockDye);
		blockFireball = new BlockMSB(BlockNames.blockFireball);
		blockSlimeball = new BlockMSB(BlockNames.blockSlimeball);
		blockRottenFlesh = new BlockMSB(BlockNames.blockRottenFlesh);
		blockPotato = new BlockMSB(BlockNames.blockPotato);
		blockNether = new BlockNether(BlockNames.blockNetherWart);
		blockGunpowder = new BlockMSB(BlockNames.blockGunpowder);
		blockCarrot = new BlockMSB(BlockNames.blockCarrot);
		blockArrow = new BlockMSB(BlockNames.blockArrow);
		blockBlazeRod = new BlockMSB(BlockNames.blockBlazeRod);
		blockFlint = new BlockMSB(BlockNames.blockFlint);
		blockBone = new BlockMSB(BlockNames.blockBone);
		blockSugar = new BlockMSB(BlockNames.blockSugar);
		blockClay = new BlockMSB(BlockNames.blockClay);
		blockString = new BlockMSB(BlockNames.blockString);
		blockFeather = new BlockMSB(BlockNames.blockFeather);
		blockBread = new BlockMSB(BlockNames.blockBread);
		blockPorkchop = new BlockPorkchop(BlockNames.blockPorkchop);
		blockFish = new BlockFish(BlockNames.blockFish);
		blockCookie = new BlockMSB(BlockNames.blockCookie);
		blockBeef = new BlockBeef(BlockNames.blockBeef);
		blockPumpkinPie = new BlockMSB(BlockNames.blockPumpkinPie);
		blockGhastTear = new BlockMSB(BlockNames.blockGhastTear);
		blockSkull = new BlockSkullStorage(BlockNames.blockSkull);
		blockMutton = new BlockMutton(BlockNames.blockMutton);
		blockRabbit = new BlockRabbit(BlockNames.blockRabbit);
		blockCompCobble = new BlockCompCobble(BlockNames.blockCompCobble);
		blockCompSand = new BlockCompSand(BlockNames.blockCompSand);
		blockCompGravel = new BlockCompGravel(BlockNames.blockCompGravel);
	}

	public static void registerBlocks() {
		GameRegistry.registerBlock(blockCharcoal, BlockNames.blockCharcoal);
		GameRegistry.registerBlock(blockApple, BlockNames.blockApple);
		GameRegistry.registerBlock(blockGoldApple, ItemBlockGoldApple.class, BlockNames.blockGoldApple);
		GameRegistry.registerBlock(blockBook, BlockNames.blockBook);
		GameRegistry.registerBlock(blockEgg, BlockNames.blockEgg);
		GameRegistry.registerBlock(blockEnder, ItemBlockEnder.class, BlockNames.blockEnder);
		GameRegistry.registerBlock(blockLead, BlockNames.blockLead);
		GameRegistry.registerBlock(blockReed, BlockNames.blockReed);
		GameRegistry.registerBlock(blockSeeds, ItemBlockSeeds.class, BlockNames.blockSeeds);
		GameRegistry.registerBlock(blockStick, BlockNames.blockStick);
		GameRegistry.registerBlock(blockLeather, BlockNames.blockLeather);
		GameRegistry.registerBlock(blockBucket, BlockNames.blockBucket);
		GameRegistry.registerBlock(blockDye, ItemBlockDye.class, BlockNames.blockDye);
		GameRegistry.registerBlock(blockFireball, BlockNames.blockFireball);
		GameRegistry.registerBlock(blockSlimeball, BlockNames.blockSlimeball);
		GameRegistry.registerBlock(blockRottenFlesh, BlockNames.blockRottenFlesh);
		GameRegistry.registerBlock(blockPotato, BlockNames.blockPotato);
		GameRegistry.registerBlock(blockNetherWart, B)

		registerBlock(blockNetherWart);
		registerBlock(blockGunpowder);
		registerBlock(blockCarrot);
		registerBlock(blockArrow);
		registerBlock(blockBlazeRod);
		registerBlock(blockFlint);
		registerBlock(blockBone);
		registerBlock(blockSugar);
		registerBlock(blockNetherStar);
		registerBlock(blockClay);
		registerBlock(blockString);
		registerBlock(blockFeather);
		registerBlock(blockBread);
		registerBlock(blockPorkchop, ItemBlockMultiMSB.class);
		registerBlock(blockFish, ItemBlockMultiMSB.class);
		registerBlock(blockCookie);
		registerBlock(blockBeef, ItemBlockMultiMSB.class);
		registerBlock(blockPumpkinPie);
		registerBlock(blockGhastTear);
		registerBlock(blockSkull, ItemBlockMultiMSB.class);
		registerBlock(blockMutton, ItemBlockMultiMSB.class);
		registerBlock(blockRabbit, ItemBlockMultiMSB.class);
		registerBlock(blockCompCobble, ItemBlockMultiMSB.class);
		registerBlock(blockCompSand, ItemBlockMultiMSB.class);
		registerBlock(blockCompGravel, ItemBlockMultiMSB.class);
	}
}
